export const DeliveryZone = [
  'Zona hotelera',
  'Playa del Carmen',
  'Puerto Morelos',
  'Costa Mujeres',
  'Tulum',
  'Boca Paila',
  'Puerto Aventuras',
  'Puerto Juarez',
  'Cancún',
  'Centro',
  'Puerto Juárez',
  'Moon Palace',
  'Now Jade',
  'Ocean Coral',
  'Turquesa Marina El Cid',
  'El Dorado Royal',
  'Mayan Palace',
  'Playa Car',
  'Xcaret',
  'Pto. Aventuras',
  'Barceló',
  'Paa Mul',
  'Isla Mujeres',
  'Excellence',
  'Playa Mujeres',
  'La Amada',
  'Villas del Palmar',
  'Akumal',
  'Las Casitas',
  'Palladium',
  'Dorado Seaside',
  'Dreams Tulum',
  'Tankah',
  'Punta Soliman',
  'Tulum Centro',
  'Bahía Príncipe',
  'Mérida (DIPAQ)',
  'Cobá',
  'Cabañas Tulum',
  'Boca Paila',
  'Valladolid',
  'Carrillo Puerto',
  'Bacalar',
  'Holbox',
  'Cozumel',
  'Chichén Itza',
  'Progreso',
  'Mahahual',
  'Punta Alen',
];
