export const DestinationsList = [
  'Paradisus',
  'RIU Palace Las Americas',
  'Hyatt Ziva',
  'Grand Oasis',
  'Hyatt Vivid',
  'Fiesta Americana Condesa',
  'The Royal Cancun',
  'Club Med',
  'Golden Parnasus',
  'Condominio Sky',
  'Dreams Sands',
  'Secrets The Vine',
  'Royalton Splash',
  'Azul Beach',
  'Excellence Riviera',
  'Marina El Cid',
  'Moon Palace',
  'Dreams Natura',
  'Senses Riviera Maya',
  'Kanai',
  'Antera',
  'The Fives',
  'Grand Hyatt',
  'Xcaret Arte',
  'The Grand Mayan',
  'Grand Riviera Princess',
  'Iberostar Riviera Maya Paraiso',
  'Wyndham Altra',
  'Fairmont Maya Coba',
  'Hyatt Zilara',
  'Av. 10 entre Calle 32 y 34',
  'Grand Luxe Jungle',
  'Ocean Riviera',
  'Excellence',
  'Mia Reef',
  'Finest Playa Mujeres',
  'Catalonia',
  'Excellence Playa Mujeres',
  'Finest Playa Mujeres',
  'Hilton',
  'Casa Malca',
  'Melia Cozumel',
  'Barcelo Maya Tropical',
  'Barcelo Maya Palace',
  'Grand Palladium',
  'Grand Sirenis',
  'Barcelo Maya Riviera',
  'TRS Yucatan',
  'Akumal Bay Beach',
  'Barcelo Maya Beach',
  'Calle 7 x 20 y 22',
];
